import {
  Stethoscope,
  HandshakeIcon,
  ShoppingCart,
  Bus,
  CheckCircle2,
  Clock,
  MessageSquare,
  Smile,
  Eye,
  MapPin,
  CreditCard,
  Ticket,
  Users,
  UtensilsCrossed,
  BookOpen,
  Scissors,
  Dog,
  Heart,
  BedDouble,
  Moon,
  CloudRain,
  Headphones,
  Home,
  PartyPopper,
  Music,
  DoorOpen,
  Armchair,
  ShieldCheck,
  Car,
  Utensils,
  HandHeart,
  Ear,
  ThumbsUp,
  Footprints,
  Baby,
  Sparkles,
  type LucideIcon,
} from "lucide-react";

export interface StoryStep {
  icon: LucideIcon;
  title: string;
  description: string;
  dialogue?: string;
  sceneColor: string;
}

export interface Story {
  id: string;
  title: string;
  subtitle: string;
  icon: LucideIcon;
  color: string;
  steps: StoryStep[];
}

export const stories: Story[] = [
  {
    id: "doctor",
    title: "Visiting the Doctor",
    subtitle: "What to expect at a checkup",
    icon: Stethoscope,
    color: "bg-calm-blue",
    steps: [
      {
        icon: Car,
        title: "Going to the Clinic",
        description: "Today we are going to see the doctor. We travel to the clinic. The building looks calm and clean inside.",
        dialogue: "We're going to see the doctor today. It will be okay.",
        sceneColor: "bg-calm-blue/30",
      },
      {
        icon: Armchair,
        title: "The Waiting Room",
        description: "We sit in the waiting room. There might be other people waiting too. You can bring a book or a comforting item to hold.",
        dialogue: "We'll wait here until it's our turn. Take your time.",
        sceneColor: "bg-sage/30",
      },
      {
        icon: MessageSquare,
        title: "Talking to the Doctor",
        description: "The doctor will say hello and ask how you feel. You can use words, point, or show them. They are here to help you.",
        dialogue: "Hi there! Can you tell me how you're feeling today?",
        sceneColor: "bg-soft-lavender/30",
      },
      {
        icon: Stethoscope,
        title: "The Checkup",
        description: "The doctor might listen to your heart, look in your ears, or check your temperature. These things don't hurt. You can ask them to explain each step.",
        dialogue: "I'm going to listen to your heart now. It won't hurt.",
        sceneColor: "bg-calm-blue/30",
      },
      {
        icon: CheckCircle2,
        title: "All Done, Going Home",
        description: "The visit is finished. You did a great job. We can go home now. You might get a sticker or a small treat.",
        dialogue: "You did so well today. I'm proud of you.",
        sceneColor: "bg-sage/30",
      },
    ],
  },
  {
    id: "meeting",
    title: "Meeting Someone New",
    subtitle: "A gentle guide to saying hello",
    icon: HandshakeIcon,
    color: "bg-sage",
    steps: [
      {
        icon: Eye,
        title: "You See Someone New",
        description: "Sometimes we meet new people. This can feel a little different. That's okay. You can take a moment before saying anything.",
        dialogue: "There's someone new here. Let's take it slowly.",
        sceneColor: "bg-sage/30",
      },
      {
        icon: HandHeart,
        title: "Saying Hello",
        description: "You can wave, nod, or say 'Hi.' You don't have to shake hands or hug. Choose what feels right for you.",
        dialogue: "Hi! It's nice to meet you.",
        sceneColor: "bg-calm-blue/30",
      },
      {
        icon: Smile,
        title: "Sharing Your Name",
        description: "You can tell them your name. They might tell you theirs too. If you forget their name later, that's okay.",
        dialogue: "My name is... What's yours?",
        sceneColor: "bg-soft-lavender/30",
      },
      {
        icon: MessageSquare,
        title: "A Short Chat",
        description: "You might talk for a little bit. If you're not sure what to say, you can ask them something simple like what they like to do.",
        dialogue: "What do you like to do?",
        sceneColor: "bg-warm-peach/30",
      },
      {
        icon: CheckCircle2,
        title: "That Went Well",
        description: "You met someone new. Even if it felt tricky, you did it. You can see them again later, or not. It's your choice.",
        dialogue: "You handled that really well.",
        sceneColor: "bg-sage/30",
      },
    ],
  },
  {
    id: "shopping",
    title: "Going Shopping",
    subtitle: "Step by step through the store",
    icon: ShoppingCart,
    color: "bg-warm-peach",
    steps: [
      {
        icon: BookOpen,
        title: "Making a List",
        description: "Before we leave, we write down what we need. A list helps us know exactly what to get. This makes the trip easier.",
        dialogue: "Let's write down what we need before we go.",
        sceneColor: "bg-warm-peach/30",
      },
      {
        icon: DoorOpen,
        title: "Arriving at the Store",
        description: "We walk into the store. It might be bright and busy. If it feels too much, it's okay to take a breath or put on headphones.",
        dialogue: "We're here. Let's take it one step at a time.",
        sceneColor: "bg-calm-blue/30",
      },
      {
        icon: MapPin,
        title: "Finding Our Items",
        description: "We walk through the aisles to find what's on our list. We can check things off as we go. This helps us stay on track.",
        dialogue: "Let's find the next item on our list.",
        sceneColor: "bg-sage/30",
      },
      {
        icon: CreditCard,
        title: "Paying at the Checkout",
        description: "We go to the checkout and wait in line. When it's our turn, we put our items down and pay. The cashier might say hello.",
        dialogue: "It's our turn now. Almost done.",
        sceneColor: "bg-soft-lavender/30",
      },
      {
        icon: CheckCircle2,
        title: "Heading Home",
        description: "Shopping is finished. You were very helpful. Let's go home and put everything away. Great job today.",
        dialogue: "You did a wonderful job helping today.",
        sceneColor: "bg-warm-peach/30",
      },
    ],
  },
  {
    id: "bus",
    title: "Taking the Bus",
    subtitle: "Your first ride, explained",
    icon: Bus,
    color: "bg-soft-lavender",
    steps: [
      {
        icon: MapPin,
        title: "Going to the Bus Stop",
        description: "We walk to the bus stop and stand near the sign. We might need to wait a few minutes. You can look for the bus number.",
        dialogue: "Our bus will come soon. We just need to wait here.",
        sceneColor: "bg-soft-lavender/30",
      },
      {
        icon: Ticket,
        title: "Getting on the Bus",
        description: "When the bus arrives, the doors will open. We let people off first, then step on. We might need to show a ticket or tap a card.",
        dialogue: "Let people off first, then we'll step on.",
        sceneColor: "bg-calm-blue/30",
      },
      {
        icon: Armchair,
        title: "Finding a Seat",
        description: "Find an empty seat and sit down. If there are no seats, hold on to a bar. The bus might be a little noisy, and that's normal.",
        dialogue: "There's a seat right there. Let's sit down.",
        sceneColor: "bg-sage/30",
      },
      {
        icon: Eye,
        title: "Watching for Our Stop",
        description: "We look out the window or listen for our stop name. When it's almost time, we press the button to tell the driver we want to get off.",
        dialogue: "Our stop is coming up. Let's press the button.",
        sceneColor: "bg-warm-peach/30",
      },
      {
        icon: CheckCircle2,
        title: "We Made It",
        description: "We step off the bus carefully. We did it. Riding the bus can feel new, but you handled it well.",
        dialogue: "You did great on the bus today.",
        sceneColor: "bg-soft-lavender/30",
      },
    ],
  },
  {
    id: "restaurant",
    title: "Eating at a Restaurant",
    subtitle: "What happens when we eat out",
    icon: UtensilsCrossed,
    color: "bg-talk-hungry",
    steps: [
      {
        icon: DoorOpen,
        title: "Arriving at the Restaurant",
        description: "We walk inside. Someone at the door might say hello and show us to a table. The restaurant might have music or other sounds.",
        dialogue: "Welcome! Let me show you to your table.",
        sceneColor: "bg-talk-hungry/30",
      },
      {
        icon: BookOpen,
        title: "Looking at the Menu",
        description: "We sit down and look at the menu. It shows what food is available. Take your time choosing. There's no rush.",
        dialogue: "Take your time looking at the menu.",
        sceneColor: "bg-warm-peach/30",
      },
      {
        icon: MessageSquare,
        title: "Ordering Your Food",
        description: "A server will come to our table and ask what we'd like. You can point to the menu, say it, or someone can help you order.",
        dialogue: "What would you like to eat today?",
        sceneColor: "bg-calm-blue/30",
      },
      {
        icon: Utensils,
        title: "Eating Your Meal",
        description: "The food arrives at our table. You can eat at your own pace. If something doesn't taste right, it's okay to say so.",
        dialogue: "Here's your food. Enjoy your meal.",
        sceneColor: "bg-sage/30",
      },
      {
        icon: CheckCircle2,
        title: "Time to Go",
        description: "When we're finished eating, we pay for the food and leave. You did well eating at a restaurant today.",
        dialogue: "That was a nice meal. Let's head home.",
        sceneColor: "bg-talk-hungry/30",
      },
    ],
  },
  {
    id: "haircut",
    title: "Getting a Haircut",
    subtitle: "A calm guide to the salon",
    icon: Scissors,
    color: "bg-talk-break",
    steps: [
      {
        icon: DoorOpen,
        title: "Arriving at the Salon",
        description: "We walk into the salon. There might be mirrors, chairs, and the sound of scissors. It's a calm place where people get haircuts.",
        dialogue: "Here we are. Let's go inside.",
        sceneColor: "bg-talk-break/30",
      },
      {
        icon: Armchair,
        title: "Waiting for Your Turn",
        description: "We might need to wait a few minutes. You can sit in a chair and bring headphones or something to hold if that helps.",
        dialogue: "We'll wait here until they're ready for you.",
        sceneColor: "bg-calm-blue/30",
      },
      {
        icon: Eye,
        title: "Sitting in the Chair",
        description: "The hairdresser puts a cape around you to keep hair off your clothes. They will start cutting gently. You can close your eyes if you'd like.",
        dialogue: "I'll put this cape on so your clothes stay clean.",
        sceneColor: "bg-sage/30",
      },
      {
        icon: Scissors,
        title: "During the Haircut",
        description: "You might hear snipping sounds and feel gentle touches on your head. If anything feels uncomfortable, you can tell them to stop.",
        dialogue: "Let me know if anything feels uncomfortable.",
        sceneColor: "bg-soft-lavender/30",
      },
      {
        icon: CheckCircle2,
        title: "All Done",
        description: "Your haircut is finished. You can look in the mirror to see how it looks. You sat so well. Time to go home.",
        dialogue: "Look at your new haircut! You did really well.",
        sceneColor: "bg-talk-break/30",
      },
    ],
  },
  {
    id: "pet",
    title: "Meeting a Pet",
    subtitle: "How to safely say hello to animals",
    icon: Dog,
    color: "bg-sage",
    steps: [
      {
        icon: Eye,
        title: "Seeing a Pet",
        description: "You see a dog, cat, or another pet. They might be on a leash or sitting near their owner. Some animals are friendly, and some need space.",
        dialogue: "Look, there's a pet over there. Let's be calm.",
        sceneColor: "bg-sage/30",
      },
      {
        icon: MessageSquare,
        title: "Asking Permission",
        description: "Before touching a pet, always ask the owner first. Say something like 'Can I pet your dog?' They will tell you yes or no.",
        dialogue: "Excuse me, can I pet your dog?",
        sceneColor: "bg-calm-blue/30",
      },
      {
        icon: HandHeart,
        title: "Saying Hello to the Pet",
        description: "Hold out your hand slowly so the animal can sniff it. Don't reach over their head. Let them come to you.",
        dialogue: "Hold your hand out gently, like this.",
        sceneColor: "bg-warm-peach/30",
      },
      {
        icon: Heart,
        title: "Petting Gently",
        description: "You can pet them gently on their back or side. Be slow and soft. If they move away, that means they need a break.",
        dialogue: "Nice and gentle. They like that.",
        sceneColor: "bg-soft-lavender/30",
      },
      {
        icon: CheckCircle2,
        title: "Saying Goodbye",
        description: "When you're done, step back calmly. You were very gentle and kind. The pet enjoyed meeting you.",
        dialogue: "You were so gentle. Well done.",
        sceneColor: "bg-sage/30",
      },
    ],
  },
  {
    id: "bedtime",
    title: "Getting Ready for Bed",
    subtitle: "A calm bedtime routine",
    icon: Moon,
    color: "bg-soft-lavender",
    steps: [
      {
        icon: Clock,
        title: "It's Almost Bedtime",
        description: "The day is ending. It's time to start getting ready for bed. We'll do a few things to help your body feel calm and sleepy.",
        dialogue: "It's almost bedtime. Let's start getting ready.",
        sceneColor: "bg-soft-lavender/30",
      },
      {
        icon: Sparkles,
        title: "Brushing Teeth and Pajamas",
        description: "We brush our teeth and put on pajamas. These are the same steps every night. Doing the same things helps us feel safe.",
        dialogue: "Let's brush teeth and put on your cozy pajamas.",
        sceneColor: "bg-calm-blue/30",
      },
      {
        icon: BookOpen,
        title: "A Quiet Moment",
        description: "You can read a book, listen to soft music, or just sit quietly. This helps your mind slow down and get ready for sleep.",
        dialogue: "Would you like to read or listen to something soft?",
        sceneColor: "bg-sage/30",
      },
      {
        icon: BedDouble,
        title: "Getting Into Bed",
        description: "Climb into bed and get comfortable. Arrange your blankets and pillow the way you like them. Everything is okay.",
        dialogue: "Get comfortable. You're safe here.",
        sceneColor: "bg-warm-peach/30",
      },
      {
        icon: CheckCircle2,
        title: "Goodnight",
        description: "Close your eyes whenever you're ready. You are safe. Tomorrow is a new day with new things to do. Goodnight.",
        dialogue: "Goodnight. You had a wonderful day.",
        sceneColor: "bg-soft-lavender/30",
      },
    ],
  },
  {
    id: "noisy",
    title: "When It Gets Too Loud",
    subtitle: "What you can do when sounds feel big",
    icon: Headphones,
    color: "bg-calm-blue",
    steps: [
      {
        icon: Ear,
        title: "Sounds Feel Big",
        description: "Sometimes sounds around you feel too loud or too much. This might happen at school, in a store, or at a gathering. This is normal.",
        dialogue: "It's okay to feel overwhelmed by sounds.",
        sceneColor: "bg-calm-blue/30",
      },
      {
        icon: CloudRain,
        title: "Notice How You Feel",
        description: "You might feel tense, want to cover your ears, or feel like leaving. These feelings are your body telling you something. Listen to them.",
        dialogue: "Your body is telling you it needs something.",
        sceneColor: "bg-soft-lavender/30",
      },
      {
        icon: Headphones,
        title: "Use Your Tools",
        description: "You can put on headphones, use ear plugs, or press your hands over your ears for a moment. These are all good choices.",
        dialogue: "You can use your headphones or ear plugs.",
        sceneColor: "bg-sage/30",
      },
      {
        icon: Footprints,
        title: "Move to a Quieter Place",
        description: "If you can, walk to a quieter spot. It's always okay to step away when you need to. You can come back when you feel better.",
        dialogue: "Let's find a quieter spot together.",
        sceneColor: "bg-warm-peach/30",
      },
      {
        icon: CheckCircle2,
        title: "Feeling Better",
        description: "Take a few slow breaths. The loud moment will pass. You knew what to do, and you did it. You handled it well.",
        dialogue: "Take a breath. You're doing great.",
        sceneColor: "bg-calm-blue/30",
      },
    ],
  },
  {
    id: "party",
    title: "Going to a Party",
    subtitle: "What to expect at celebrations",
    icon: PartyPopper,
    color: "bg-warm-peach",
    steps: [
      {
        icon: Car,
        title: "On the Way",
        description: "We are going to a party. There will be other people there. Before we go, we can talk about what to expect so you feel ready.",
        dialogue: "Let's talk about what the party might be like.",
        sceneColor: "bg-warm-peach/30",
      },
      {
        icon: DoorOpen,
        title: "Arriving",
        description: "When we get there, take a moment to look around. Find a quiet spot you can go to if you need a break. It's good to have a plan.",
        dialogue: "Let's find a calm spot, just in case you need it.",
        sceneColor: "bg-calm-blue/30",
      },
      {
        icon: Users,
        title: "Being Around Others",
        description: "You can say hello, play games, eat snacks, or just watch. There's no rush to join in. Do what feels comfortable for you.",
        dialogue: "You can join in whenever you're ready.",
        sceneColor: "bg-sage/30",
      },
      {
        icon: Music,
        title: "If It Gets Too Much",
        description: "Parties can be loud or busy. If you need a break, it's okay to step away for a few minutes. You can always come back.",
        dialogue: "Need a break? That's completely fine.",
        sceneColor: "bg-soft-lavender/30",
      },
      {
        icon: CheckCircle2,
        title: "Time to Go",
        description: "When it's time to leave, say goodbye. You did great being around other people today. It's okay if you felt tired.",
        dialogue: "You did really well at the party today.",
        sceneColor: "bg-warm-peach/30",
      },
    ],
  },
];
